### ISSUE TITLE
fs_upload() sudden issue with specific csv file

### ISSUE THREAD

**Issue by majazaloznik** [ropensci/rfigshare#108]
`fs_upload()` has stopped working on [this file ](https://github.com/majazaloznik/ProspectiveAgeData/blob/master/data/04_human-readable/2017_prospective-ages.csv) to [this deposit](https://figshare.com/articles/Prospective_Age_Dataset/6974414) fileset. 
it worked fine until version 18, after that only the two pdfs upload ok, but not the csv file. the file is 774MB, so the size shouldn't be an issue?

**Comment by majazaloznik** [comment]
OK, was my mistake, the file was 100 times larger than it should have been, after fixing my code it's back to 7MB, which works fine. 

Still, I thought individual files can be up to 5 GB, so size should not have been an issue here?

**Comment by cboettig** [comment]
Thanks for the follow-up.  Note that you can usually get substantial reductions in file size by compressing csv's first as well, e.g. `readr::write_csv(big_data, "myfile.csv.xz")` will automatically compress the file.
