### ISSUE TITLE
authentication on a headless server

### ISSUE THREAD

**Issue by adityabandla** [ropensci/rfigshare#115]
I am trying to use rfigshare to upload files from a remote headless server. Is there a way to get the authentication done without a browser?

**Comment by muschellij2** [comment]
1. Save OAuth Token to RDS
2. Assign token to `oauth`:
```r
token = readr::read_rds("/path/to/token.rds"))
assign("oauth", token, envir = rfigshare:::FigshareAuthCache)
```
Run code.

**Comment by jhrcook** [comment]
I just made a new article locally using `fs_create()`, authenticated through the browser, and then moved the ".httr-oauth" file that was created to my remote server. Not much of a fix, but hopefully it helps someone in the future.
