### ISSUE TITLE
fs_download does not work on private datasets (figshare API bug)

### ISSUE THREAD

**Issue by karthik** [ropensci/rfigshare#47]
To replicate, create a dataset. Upload. Set to private. Then try downloading with `mine = TRUE`. Does not work.

**Comment by cboettig** [comment]
Looks like this still has not been added to the API.  

If you get `fs_details` on a public vs a private item, you see these fields for files:

```
 names(public$items[[1]]$files[[1]])
[1] "thumb"        "download_url" "name"         "id"           "mime_type"   
[6] "size"        
> names(private$items[[1]]$files[[1]])
[1] "size"      "thumb"     "id"        "mime_type" "name"     
> 
````

private has no `download_url`, despite the feature now being available on the web interface as linked above.

**Comment by beausoleilmo** [comment]
It seems that now the download URL is present, but I still get a 403 error

**Comment by cboettig** [comment]
Please take a look at https://docs.ropensci.org/deposits/ instead
