### ISSUE TITLE
fs_auth is behaving weirdly

### ISSUE THREAD

**Issue by karthik** [ropensci/rfigshare#92]
@cboettig 

When I auth now, I get to this page:

![image](https://cloud.githubusercontent.com/assets/138494/8434488/e092f41e-1f4b-11e5-950e-5ea327ac4f1e.png)

Then see this in a separate part of my applications:

![image](https://cloud.githubusercontent.com/assets/138494/8434505/f1e50ba8-1f4b-11e5-8c55-ddf4b57df3f9.png)

But when I upload files, they go somewhere mysterious:

``` r
library(rfigshare)
fs_auth()
id <- fs_create("title", "description","dataset")
write.csv(iris, file = "dat.csv")
(x <- fs_upload(id, "dat.csv"))
```

Returns `NULL`. But that's ok I suppose. Then this happens:

``` r
> figshare_clean <- function(x) {
+   data.frame(t(unlist(x)), stringsAsFactors = FALSE)
+ }

> results <- dplyr::rbind_all(sapply(fs_browse(), figshare_clean))

>
> results
Source: local data frame [10 x 24]

   article_id                     title master_publisher_id defined_type status
1     1468431                     title                   0      dataset Drafts
2     1468430                     title                   0      dataset Drafts
3     1468426         Fisheries dataset                   0      dataset Drafts
4     1468425         Fisheries dataset                   0      dataset Drafts
5     1468424         Fisheries dataset                   0      dataset Drafts
6     1468423         Fisheries dataset                   0      dataset Drafts
7     1094836 This is now the new title                   0      dataset Drafts
8     1094835                     title                   0      dataset Drafts
9     1089650         Fisheries dataset                   0      dataset Drafts
10    1088435         Fisheries dataset                   0      dataset Drafts
Variables not shown: version (chr), published_date (chr), description (chr),
  description_nohtml (chr), total_size (chr), authors.first_name (chr),
  authors.last_name (chr), authors.id (chr), authors.full_name (chr),
  authors.first_name.1 (chr), authors.last_name.1 (chr), authors.id.1 (chr),
  authors.full_name.1 (chr), tags.id (chr), tags.name (chr), categories.id
  (chr), categories.name (chr), links.link (chr), links.id (chr)
```

None of these files are in my primary figshare account which I authorized with: 

![image](https://cloud.githubusercontent.com/assets/138494/8434619/b9262332-1f4c-11e5-94ac-48205aab23ea.png)

So color me confused. Where did these go?

**Comment by cboettig** [comment]
Good question.  I would bet the files are somehow getting uploaded to the test account instead of your account, but who knows.  The API is a bit of a mess (queries returning wrong or missing results, formatting issues, etc; I think Arfon also had some issues with it in working on the software import) and so I haven't done much with the package for a long time.  Clearly I should be doing a better job as maintainer, but too many other things.  

I think the use case for programmatic upload is stronger in cases where there is more metadata such that online upload forms become tedious.  I'm not sure the current use cases are as compelling in figshare context (to me anyway).  So, color me with excuses.

**Comment by karthik** [comment]
Ok. Thanks Carl. 
I was updating a demo for tomorrow but I realized Figshare is becoming less and less usable. Will be the last time I speak about them.

**Comment by jcolomb** [comment]
"Figshare is becoming less and less usable:”
you mean Rfigshare, the figshare API or figshare itself? 
what are the other options, then?

**Comment by cboettig** [comment]
@jcolomb Right, `rfigshare` and the API; I don't think these issues impact the figshare web interface

**Comment by karthik** [comment]
Sorry. I meant the API. It's become more difficult yet to use. No reflection on this package itself.
