### ISSUE TITLE
error: "Internal Server Error" - fs_get_auth

### ISSUE THREAD

**Issue by AugustT** [ropensci/rfigshare#93]
Hi,

We are using rfigshare in the ZOON package ([over here](https://github.com/zoonproject)) and I'm having some issues today. When rfigshare tries to authenticate I get a "Internal Server Error" in my browser. Is this a known issue, a known intermittent issue or something new?

I can replicate this on my machine by simply running

``` r
rfigshare:::fs_get_auth()
```

Any help appreciated as I'm supposed to be doing a live demo in the next few days!

Tom

**Comment by AugustT** [comment]
`fs_auth()` produces the same error

**Comment by goldingn** [comment]
Just to add that I can replicate both on a mac & on a different network

**Comment by cboettig** [comment]
hmm... nope, that's somewhat new; looks like it might be a problem with the figshare API?  We'll get in touch with there team and investigate.

Meanwhile, just wanted to let you know, here at rOpenSci we've not been super happy with the figshare API, (guess it's somewhat tangential to their core business model), and have a few related packages in the works for other databases (e.g. zenodo, or for a more metadata rich approach, a combination of dataone+EML).  Anyway, will see if we can get figshare auth back online.

**Comment by AugustT** [comment]
@cboettig Thanks for looking into this for us, in teh short term it would be great to have a figshare fix. 

Following your train of thought we would appreciate your option on whether we should continue using figshare in light of your comments. We use it as a means to allow people to share their analyses with other users of our package. If you think this would be better done via another platform & R-package we would be keen to know. For us I think the key requirements are that the analysis get a DOI, can accept metadata (authors, description, ...) and that they can be sent and received easily (and reliably!) from R.

**Comment by jcolomb** [comment]
Just seen this from figshare:
Currently transitioning to new code base. Please bear with us while we line up all of the pipes again :)

This probably explain the problems...

On 9 December 2015 18:31:33 CET, Dr Tom August <notifications@github.com> wrote:
>@cboettig Thanks for looking into this for us, in teh short term it
>would be great to have a figshare fix. 
>
>Following your train of thought we would appreciate your option on
>whether we should continue using figshare in light of your comments. We
>use it as a means to allow people to share their analyses with other
>users of our package. If you think this would be better done via
>another platform & R-package we would be keen to know. For us I think
>the key requirements are that the analysis get a DOI, can accept
>metadata (authors, description, ...) and that they can be sent and
>received easily (and reliably!) from R.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ropensci/rfigshare/issues/93#issuecomment-163333332

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by cboettig** [comment]
rfigshare has been deprecated in favor of https://github.com/ropenscilabs/deposits
