### ISSUE TITLE
Poor help page for fs_download()

### ISSUE THREAD

**Issue by oharar** [ropensci/rfigshare#95]
The fs_download() help page describes the function with "Get details for an article", which is the same as fs_details(). It also doesn't say what the function returns, so when I do this:

> fs_download(4415482, urls_only = TRUE)
> NULL

I'm not sure what's meant to happen, but can't be sure. (also - would it be better to give a warning when a NULL is returned?)

It turned out I was using the wrong ID, but it was hell trying to track down the problem (UI had a bit of a rant about it on twitter. Sorry). It's not obvious from the documentation what the correct ID should be. It might be helpful to have a section in Getting Started on how to download data, starting from the Figshare page. Finding the right IDs isn't covered and there appear to be 2 long numbers that could be IDs (in my case I wanted 2729782, which pointed to https://ndownloader.figshare.com/files/4415482).

**Comment by sckott** [comment]
Thanks for the issue @oharar - We'll improve the docs.

**Comment by sckott** [comment]
We're in the process of trying to integrate with the new figshare web services, so will update these docs when that's sorted out

**Comment by cboettig** [comment]
rfigshare has been deprecated in favor of https://github.com/ropenscilabs/deposits
