### ISSUE TITLE
Just use PATs for auth?

### ISSUE THREAD

**Issue by sckott** [ropensci/rfigshare#97]
Any objection to simply having rfighsare users generate a personal access token for rfigshare ? instead of using OAUTH dance

They require https for url redirect on oauth dance, which i at  least can’t sort out how to work

But users could generate their own PAT, then we can just use that

**Comment by sckott** [comment]
cc @cboettig @karthik

**Comment by jcolomb** [comment]
Hi. 
I do not  get the implications. I am planning to include an upload in figshare function in cetran for the mozsprint. Can it affect how the user will have to use it?

**Comment by sckott** [comment]
Changes will not be made on master branch here, so won't affect master right away. 

With a Personal Access Token, a user will have to go to their account, go to Applications, then generate a token. Then they'd use that in this package. That would be instead of the oauth workflow now where users get the browser tab to open, etc. 

We'd like to stock with OAuth, but the new Figshare API requires https for redirect URLs, and with a local workflow in R, i don't think there's any way to have a localhost https url - They said they're thinking about not requiring https when a URL is localhost, but who knows when that will change

**Comment by cboettig** [comment]
I believe you can do HTTPS on localhost, you wound just need to provide a certificate (probably nust a self-signed one would be good enough here).  We could add that to the package but not sure if it is worth the hassle

**Comment by sckott** [comment]
interesting, will look into that

**Comment by ethanwhite** [comment]
I just ran into PATs not being an option yesterday and it would be really useful for us.

@sckott - what's the state of development on the branch you started?

**Comment by sckott** [comment]
@ethanwhite thanks for the question - status is I just haven't gotten around to finishing it up :(

**Comment by cboettig** [comment]
rfigshare has been deprecated in favor of https://github.com/ropenscilabs/deposits
