### ISSUE TITLE
Testing Rfigshare with new API

### ISSUE THREAD

**Issue by jcolomb** [ropensci/rfigshare#98]
fs_download (fighsarenumber) is still working.
fs_create is working too.
testing upload later

**Comment by jcolomb** [comment]
upload is working too.

**Comment by jcolomb** [comment]
oups, I was using old application credentials which are using the API v1 !!!
Any way to get figshare to give the option to choose the v1 of their API until rfigshare is developed further?

**Comment by jcolomb** [comment]
I contacted figshare:
Dear figshare team,

The Rfigshare package is presently using the APIv1 and works perfectly fine with old accounts. There is but no way to make a new application on a new account using the APIv1, such that I cannot use figshare with new accounts.

Would there be a way to create APIv1 application in new accounts, at least for 6 months to give time to the developers to build a new Rfigshare system?

Best,
Julien Colomb

**Comment by sckott** [comment]
@jcolomb you did install from branch `sckott`, correct?

**Comment by sckott** [comment]
I think the master branch of this repo still uses the old API

**Comment by jcolomb** [comment]
response from figshare:
Hey Julien,

I'm afraid this isn't possible with the V1 API. While it is supported, all new apps need to go through V2.

Is there any way we can support you with getting up to speed on this?

Thanks,

Mark

Yes the master use the old API, this means I can still use it with my account since the API is still supported, but all new app need to go v2... I will check your branch now!

**Comment by jezcope** [comment]
Is there any news on this? If the v1 API hasn't stopped working yet, it will do soon, and I'm keen to publicise this module to R users at my university as we use figshare as an institutional data catalogue/repository. I'm happy to contribute if I can but my R knowledge is pretty basic and mostly theoretical!

I know figshare are currently looking to encourage more people to use the API, so there may be opportunities there too.

**Comment by sckott** [comment]
@jezcope good to hear that people want to use it. It's been painful to work with their web services, so we do need encouragement to do so. I'll put it on the to do list

**Comment by jezcope** [comment]
@sckott They're practicing API-first development now AFAICT, so things are a lot better. You can now do pretty much anything you can do in the UI through the v2 API (in some cases more), though the docs are still shocking. The collections feature appeared in the API months before the UI for it was implemented, for example. They're very prompt at answering queries at http://support.figshare.com/ and generally keen to encourage more API use. I'll point them here to see if they can provide any input.

Let me know if I can do anything else!

**Comment by jcolomb** [comment]
They are also involved in the opencon satellite event in berlin (with overleaf and scienceopen) It would be great to have the rfigshare api working for the hackathon on friday 22th november I think.
Or developing new functions for rfigshare could a theme of the hackathon...

Am 29. September 2016 09:54:21 MESZ, schrieb Jez Cope <notifications@github.com>:
>@sckott They're practicing API-first development now AFAICT, so things
>are a lot better. You can now do pretty much anything you can do in the
>UI through the v2 API (in some cases more), though the docs are still
>shocking. The collections feature appeared in the API months before the
>UI for it was implemented, for example. They're very prompt at
>answering queries at http://support.figshare.com/ and generally keen to
>encourage more API use. I'll point them here to see if they can provide
>any input.
>
>Let me know if I can do anything else!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ropensci/rfigshare/issues/98#issuecomment-250396480

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by jezcope** [comment]
@jcolomb That would be great — either getting the module up to scratch before the hackathon or working on it there. I can't attend the hackathon in person but I'd certainly be able to contribute remotely if that's an option.

**Comment by cboettig** [comment]
rfigshare has been deprecated in favor of https://github.com/ropenscilabs/deposits
